
name: Hello World Workflow
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  run-script:
    runs-on: windows-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Run main.ps1
        shell: pwsh
        run: ./.github/workflows/main.ps1
 
